[config]
response_language = "en-US"

[pr_reviewer]
require_tests_review = true
require_security_review = true
require_can_be_split_review = true
num_code_suggestions = 4

[pr_description]
publish_labels = true
add_original_user_description = true
generate_ai_title = true

[pr_code_suggestions]
commitable_code_suggestions = true
focus_only_on_problems = true
